-- Create uploads table to track usage
create table if not exists public.uploads (
  id bigint generated by default as identity primary key,
  user_id text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.uploads enable row level security;

-- Create policy to allow server-side operations (Service Role will bypass, but good to have)
create policy "Enable insert for authenticated users only"
  on public.uploads for insert
  with check (true);

create policy "Enable read for authenticated users only"
  on public.uploads for select
  using (true);

-- Indexes for performance
create index if not exists uploads_user_id_idx on public.uploads (user_id);
create index if not exists uploads_created_at_idx on public.uploads (created_at);
